import View from "../components/View";
import Intelligence from "../components/Intelligence";
const gdi_routes = [
    {
        path: '/eva/:id',
        component: View,
        props: {
            menu_items: [
                {index: 1, title: 'GDI InOps', dest: '/eva/inops',
                    children: [
                        {index: 1, title: '驻军', dest: 'garrisoning'},
                        {index: 2, title: '呼叫运输机', dest: 'calling_for_transport'},
                        {index: 3, title: '后勤物资箱', dest: 'logistics_crates'},
                        {index: 4, title: '液态泰伯利亚研究', dest: 'liquid_tiberium_research'},
                        {index: 5, title: 'Nod兄弟会飞行器', dest: 'nod_aircraft'},
                        {index: 6, title: '新式Nod喷火坦克', dest: 'flame_tank'},
                        {index: 7, title: '征用泰伯利亚储藏柱', dest: 'tiberium_spikes'},
                        {index: 8, title: 'EMP控制中心', dest: 'emp_centre'},
                        {index: 9, title: '开罗的核弹发射井', dest: 'cairo_nuclear'},
                        {index: 10, title: 'Nod兄弟会的核武器库', dest: 'nod_nuclear'},
                        {index: 11, title: 'Nod离子炮干扰科技', dest: 'ion_cannon_disruption'},
                        {index: 12, title: '声波武器与外星侵略者', dest: 'sonic&invader'},
                        {index: 13, title: '外星人的起源及其与塔西佗的连接', dest: 'alien&tactitus'},
                    ]},
                {index: 2, title: 'GDI新闻专线', dest: '/eva/news'},
                {index: 3, title: 'GDI前线纪实', dest: '/eva/eyewitness'},
                {index: 4, title: 'GDI军备，战术与系统', dest: '/eva/military',
                    children: [
                        {index: 1, title: 'GDI步枪兵', dest: 'riflemen'},
                        {index: 2, title: 'GDI导弹兵小队', dest: 'missile_squad'},
                        {index: 3, title: 'GDI工兵', dest: 'gdi_engineer'},
                        {index: 4, title: '机动基地车', dest: 'mcv'},
                        {index: 5, title: '兵营', dest: 'barracks'},
                        {index: 6, title: 'APC', dest: 'apc'},
                        {index: 7, title: '掷弹兵', dest: 'grenadier'},
                        {index: 8, title: '狙击小队', dest: 'sniper_team'},
                        {index: 9, title: '指挥部', dest: 'command_post'},
                        {index: 10, title: '机场', dest: 'airfield'},
                        {index: 11, title: '奥卡攻击机', dest: 'orca'},
                        {index: 12, title: '突击队员', dest: 'commando'},
                        {index: 13, title: '捕食者主战坦克', dest: 'predator'},
                        {index: 14, title: 'GDI基地防御建筑', dest: 'base_defense'},
                        {index: 15, title: '起重机', dest: 'crane'},
                        {index: 16, title: '战区重装兵', dest: 'zone_troopers'},
                        {index: 17, title: '战争工厂的维修无人机', dest: 'repair_drone'},
                        {index: 18, title: '使用勘探者进行基地扩张', dest: 'surveyor'},
                        {index: 19, title: '雷格：展开成为作战基地', dest: 'rig'},
                        {index: 20, title: '火鹰战机', dest: 'firehawk'},
                    ]},
                {index: 5, title: 'GDI档案室', dest: '/eva/archives'},
            ]
        },
        children: [
            {
                path: 'riflemen',
                component: Intelligence,
                props: {
                    title: 'GDI步枪兵 Riflemen',
                    translation: [
                        '装备有GD2型步枪的GDI步枪兵，是GDI军队的中流砥柱。',
                        '接受过反步兵作战技术训练的他们被部署在所有战区。',
                        '步枪兵在防御建筑中时作用最为显著，当需要防守固定地点时，他们还携带了用于挖掘散兵坑的装备。',
                        '在缺乏足够强力的重武器支援的情况下，无论如何步枪兵都不应直面敌方的重型装甲单位，特别是敌军还拥有喷火武器时。',
                    ],
                    original: [
                        'Equipped with the GD2 rifle, GDI Riflemen are the mainstay of GDI military forces.',
                        'They are deployed to all combat zones and trained in anti-infantry combat techniques.',
                        'Riflemen are most effective when garrisoned in fortified structures, and are equipped to dig foxholes when the need arises to defend a fixed position.',
                        'Riflemen should never be deployed against heavy armor,especially flame weapons, without significant heavy-weapon Support.',
                    ],
                    tr_source: '【战地手册-基础步兵】',
                    tr_remark: 'GDI - 作战单位与武器',
                    or_source: 'Field Manual - Basic Infantry',
                    or_remark: 'GDI - Units and Weapons',
                },
            },
            {
                path: 'missile_squad',
                component: Intelligence,
                props: {
                    title: 'GDI导弹兵小队 Missile Squad',
                    translation: [
                        'GDI导弹兵小队统一装备有用于最大限度毁伤战车和飞行器的FGM-90。',
                        '像吉普车或越野车这样的轻型战车是导弹兵小队的绝佳攻击目标。',
                        '导弹兵小队通常与规模更大的步枪兵小队联合行动，不过当他们位于民居或APC这样能为他们阻挡反步兵火力的驻军点中时，他们的作战效果相当可观。',
                    ],
                    original: [
                         'GDI Missile Squads are armed with the FGM-90, which is designed to inflict maximum damage to vehicles and aircraft.',
                         'Light vehicles like jeeps and buggies are excellent targets for Missile Squads.',
                         'Missile Squads are normally deployed in tandem with larger Rifleman squads, but can be used to great effect from garrisoned positions in civilian buildings or APCs where they are protected from anti-infantry fire.',
                    ],
                    tr_source: '【战地手册-基础步兵】',
                    tr_remark: 'GDI - 作战单位与武器',
                    or_source: 'Field Manual - Basic Infantry',
                    or_remark: 'GDI - Units and Weapons',
                },
            },
            {
                path: 'gdi_engineer',
                component: Intelligence,
                props: {
                    title: 'GDI工兵 Engineer',
                    translation: [
                        'GDI战地工程师能够占领敌方建筑并修理受损的建筑（包括桥梁和基地建筑）。',
                        '指挥官可以派遣一名工程师潜入敌方基地建筑内从而将其占据——或者令其进入一座受损的建筑进行彻底的修复。',
                        '派遣一名工程师进入桥梁自动维修门楼内，可修缮损毁的桥梁。',
                        '作为一名战地工程师，一些至关重要的行为准则应被永远牢记于心：',
                        '1. 绝不在敌占区内单独行动。你身着的标准配置防弹衣在大多数现代武器面前不堪一击。',
                        '2. 你装备有一把标准GD45型袖珍手枪，仅将其作为你别无选择时的手段，因为它无法击穿大多数现代装甲或护甲。',
                        '3. 一旦你成功进入了敌方建筑物，一定要以最快速度使中央计算机终端停止运转，并安装你的覆盖程序，从而与距离你最近的GDI指挥部取得连接。',
                        '4. 当你进入一座受损建筑时，确保你能够启动损害管制程序使其迅速运行完毕。在自动损管系统发挥作用后，你将会明确该如何着手于更加繁复和规模更加庞大的维修工作。',
                        '5. 永远戴好你的安全帽。',
                    ],
                    original: [
                        'GDI combat engineers are able to capture enemy buildings and repair structures (including bridges and base buildings).',
                        'Deploy an engineer into an enemy base structure in order to capture it - or send an engineer into a damaged building to fix it back up again.',
                        'Damaged bridges can be repaired by deploying an engineer into the bridge auto-repair gatehouses.',
                        'As a combat engineer a few cardinal rules should be kept in mind at all times:',
                        '1. Never act alone in hostile territory. Your standard issue body armor is ineffective against most modern weapons.',
                        '2. You are equipped with a standard GD45 sidearm. Only use it as a last resort as it will not penetrate most modern body armor.',
                        '3. Once you gain access to an enemy structure be sure to disable the central computer terminal immediately and install your override program to connect the structure to the nearest command post.',
                        '4. When entering a damaged structure be sure to initiate damage control programs for immediate results. Once the automation has kicked in you will be clear to commence more extensive repairs.',
                        '5. Keep your hard-hat on at all times.',
                    ],
                    tr_source: '【节选自 战地工程师教材】',
                    tr_remark: 'GDI - 作战单位与武器',
                    or_source: 'Engineer Combat Primer Excerpt',
                    or_remark: 'GDI - Units and Weapons',
                },
            },
            {
                path: 'mcv',
                component: Intelligence,
                props: {
                    title: '机动基地车 M.C.V.',
                    translation: [
                        '作为一座前沿基地的根基与核心，机动基地车（MCV）被部署在所有主要战场。',
                        'MCV能够在一切障碍相对较少的地形上行进。',
                        'MCV不具备任何自卫能力。',
                        '当一辆MCV抵达它的目的地时，它可以立即迅速展开成为一座建筑工厂，能够建造生产建筑，泰伯利亚精炼厂和其它前沿基地所需要的建筑物。',
                        '建筑工厂可以随时被收起从而回到机动的MCV形态，但我们的建议是，仅当建筑工厂所支持的基地不再使用时才将其收起。',
                    ],
                    original: [
                        'Mobile Construction Vehicles, or MCVs, are deployed to all major theatres to serve as the foundation for a forward operating base.',
                        'The MCV is capable of rolling over any relatively clear terrain.',
                        'It\'s not equipped for self-defense.',
                        'When an MCV reaches its destination it can immediately unpack into a construction Yard capable of building production structures, a Tiberium Refinery, and other elements needed for a forward base.',
                        'The Construction Yard can be packed up into the MCV at any time, although it is only advised when the base it supports is no longer being used.',
                    ],
                    tr_source: '【战地工程师教材】',
                    tr_remark: 'GDI - 作战单位与武器',
                    or_source: 'Engineer Combat Primer',
                    or_remark: 'GDI - Units and Weapons',
                },
            },
            {
                path: 'barracks',
                component: Intelligence,
                props: {
                    title: '兵营 Barracks',
                    translation: [
                        'GDI的大本营由许多高度便携式和模块化的建筑组成。',
                        '这使得在恶劣气候下和偏远地区中建造和拆除居所变得轻松快捷。',
                        '在持久耐用的装甲镀层板保护下，驻扎在GDI基地的人员能够免受泰伯利亚污染和离子风暴的影响，但是如果没有兵工厂的支援，他们将无法获取先进的武器装备。',
                    ],
                    original: [
                        'GDI base camps are created using highly portable，modular buildings.',
                        'This allows for easy construction and tear-down of shelters in harsh climates and remote locations.',
                        'Personnel stationed at GDI bases will find themselves protected from Tiberium contamination and ion storms due to the durable armor plating, but will not have access to advanced weaponry without the support of an Armory.',
                    ],
                    tr_source: '【战地手册-后勤保障】',
                    tr_remark: 'GDI - 作战单位与武器',
                    or_source: 'Field Manual - Logistics',
                    or_remark: 'GDI - Units and Weapons',
                },
            },
            {
                path: 'apc',
                component: Intelligence,
                props: {
                    title: '装甲运兵车 APC',
                    translation: [
                        'GDI装甲运兵车(APC)，是一种通过装甲舱室运输士兵的六轮全地形车辆。',
                        '可调节尺寸的枪眼让车内士兵能够向车外目标开火。',
                        '在APC中部署一队导弹兵，APC就可以发射导弹。',
                        'APC具有多个出口，因此乘员可以迅速撤离，从而能够以最短的准备时间进入露天交火状态。',
                    ],
                    original: [
                        'The GDI Armored Personnel Carrier, or APC, is a six-wheeled all-terrain vehicle that can transport infantry in an armored compartment.',
                        'Dynamically sized fire slits permit the soldiers riding in the vehicle to shoot at targets outside the APC.',
                        'Deploy a Missile Squad into an APC and the vehicle effectively gains the ability to fire missiles.',
                        'Passengers can be evacuated quickly through multiple exits from the APC, so the vehicle can drop soldiers right into a firefight with minimum downtime for unloading.',
                    ],
                    tr_source: '【战地手册-APC】',
                    tr_remark: 'GDI - 作战单位与武器',
                    or_source: 'Field Manual - APC',
                    or_remark: 'GDI - Units and Weapons',
                },
            },
            {
                path: 'sniper_team',
                component: Intelligence,
                props: {
                    title: '狙击小队 Sniper Team',
                    translation: [
                        '狙击小队能够几乎弹无虚发地击杀敌方步兵。',
                        '他们运用了隐形技术，在静止时不会被肉眼观测到，也不会被普通设备探测到。',
                        '狙击小队中的观察手具有非凡的指示能力，让指挥官可以在半径数英里的范围内为神像火炮机甲指定攻击目标。',
                        '在战场上，神像的机组人员可以观察并锁定为他们指示目标的狙击小队四周的一切敌方单位和建筑。',
                    ],
                    original: [
                        'Sniper Teams are able to take down enemy infantry with deadly precision.',
                        'They employ stealth so they can\'t be seen or detected while motionless.',
                        'Finally, the spotter in a Sniper Team allows you to designate targets for any Juggernaut artillery unit for miles around.',
                        'The Juggernaut crew will be able to see and target enemy units and structures anywhere near active Sniper Teams in the environment.',
                    ],
                    tr_source: '【战术行动战地指南：狙击小队】',
                    tr_remark: '',
                    or_source: 'TacOps Field Guide: Sniper Team',
                    or_remark: '',
                },
            },
            {
                path: 'grenadier',
                component: Intelligence,
                props: {
                    title: '掷弹兵 Grenadier',
                    translation: [
                        '如果你想迅速清扫一座驻军建筑物，只需派出一队掷弹兵，他们就可以完成这项任务。',
                        '他们投掷的火箭助推手榴弹甚至可以打击高大建筑的顶层。',
                        '更令人赞叹的是，手榴弹上配备了微型AI和制导系统，能够控制飞行路线，使手榴弹直接通过窗户进入建筑。',
                        '掷弹兵能够把驻守在建筑内的敌军士兵炸飞。',
                    ],
                    original: [
                        'If you need to clear a garrisoned building fast, deploy a Grenadier squad and they\'ll get the job done.',
                        'Their rocket propelled grenades can even hit the upper stories of taller structures.',
                        'Even better, the grenades have minimal on-board AI and guidance and steer themselves right through windows.',
                        'Grenadiers will blow the garrisoned enemy troops right out of the side of the building.',
                    ],
                    tr_source: '【战术行动战地指南：掷弹兵小队】',
                    tr_remark: '',
                    or_source: 'TacOps Field Guide: Grenadier Squad',
                    or_remark: '',
                },
            },
            {
                path: 'command_post',
                component: Intelligence,
                props: {
                    title: '指挥部 Command Post',
                    translation: [
                        '在所有战区，在任何天气条件下，GDI前沿基地都扮演着GDI军事行动的枢纽。',
                        '而GDI前沿基地的心脏就是指挥部。',
                        '战地指挥官通过指挥部与各区域的GDI资源保持联系，在指挥部中聚合情报，从而迅速对局势变化做出应对。',
                        '大功率雷达和通讯设备让军官们能够获取来自战场的即时反馈，但请特别留意，这些设备会大量消耗你的基地电网产生的电力。',
                    ],
                    original: [
                        'GDI forward bases act as the hubs for GDI operations in all Zones and weather conditions.',
                        'The heart of any GDI forward base is the Command Post.',
                        'From this structure field commanders can maintain contact with regional GDI resources and centralize intelligence for rapid response.',
                        'High-powered radar and communications equipment allow officers real-time feedback from units in the field, but note that this gear will draw significant power from your base grid.',
                    ],
                    tr_source: '【战地手册-指挥所】',
                    tr_remark: '',
                    or_source: 'Field Manual - Command Structure',
                    or_remark: '',
                },
            },
            {
                path: 'airfield',
                component: Intelligence,
                props: {
                    title: '机场 Airfield',
                    translation: [
                        '空军部队通常用于支援特定的地面力量。',
                        '一座模块化的GDI机场建成后，它可以无限期地维护多达四架战机。',
                        '机场能够为奥卡攻击机提供加油、维修和装弹服务，也可以通过加装先进的科技设备对垂直起降式火鹰战机进行维护。',
                        '机场直接控制着每架战机的一小部分工作单元，所以失去机场的支持和联络，这些战机的导航系统可能会出现故障，同时考虑到全球性的离子风暴的干扰，战机可能会失去延程飞行的能力。',
                    ],
                    original: [
                        'Air assets are often dedicated to support a particular ground force.',
                        'The modular GDI Airfield can be established to maintain up to four combat aircraft indefinitely.',
                        'The facility is capable of refueling, repairing,and rearming Orca ground attack aircraft, but can also sustain Firehawk VTOL attack jets with the addition of advanced technical equipment.',
                        'Airfields each directly control a small element of aircraft, so without an Airfield these craft may suffer guidance failure and the inability to maintain extended operations considering global ion storm interference.',
                    ],
                    tr_source: '【战地手册-前沿空军基地】',
                    tr_remark: '',
                    or_source: 'Field Manual - Forward Air Bases',
                    or_remark: '',
                },
            },
            {
                path: 'orca',
                component: Intelligence,
                props: {
                    title: '奥卡攻击机 Orca Attack Aircraft',
                    translation: [
                        '数十年以来，具有高机动性且体质轻盈的奥卡空中武器平台一直在支援着GDI的地面作战。',
                        '当前与其它GDI军事力量一同部署在世界各地的奥卡Mk Ⅳ，是一种具有顶尖技术水平的全新战机。',
                        '奥卡Mk Ⅳ可以垂直起降，具有微型操作终端，高巡航速度，超长射程以及长时间悬停的能力，它是一种真正的多功能武器系统。',
                        '它挂载的空对地导弹可以对各种各样的目标实施打击，包括敌方战车和建筑物。',
                        '奥卡Mk Ⅳ还可以装载一个传感器阵列，即使是运用最先进隐形技术的Nod单位也会被侦测到。',
                        '战地指挥官应特别留意奥卡攻击机不具备空战能力，当在Nod兄弟会握有空中优势的地区行动时，应派遣挂载空对空导弹的火鹰战机护卫奥卡攻击机。',
                    ],
                    original: [
                        'The highly maneuverable and light-weight Orca aerial weapons platform has supported GDI ground campaigns for decades.',
                        'The Mk Ⅳ version currently deployed with GDI forces worldwide is an all-new, state-of-the art aircraft.',
                        'With VTOL capability that allows it to operate from small pads, a high cruising speed, long range, and the ability to hover for extended periods, the Mk Ⅳ Orca is a truly versatile weapon system.',
                        'Its air-to-ground missiles can strike a wide variety of targets including enemy vehicles and structures.',
                        'The Mk Ⅳ can also be equipped with a sensor array capable of detecting even the most advanced Nod stealth units.',
                        'Field commanders should note that Orcas are not capable of engaging targets in the air and should be escorted by Firehawk attack jets carrying air-to-air missiles when operating in areas where Nod commands air superiority.',
                    ],
                    tr_source: '【战术行动战地指南：奥卡Mk Ⅳ】',
                    tr_remark: '',
                    or_source: 'TacOps Field Guide: Mark Ⅳ Orca',
                    or_remark: '',
                },
            },
        ]
    }
    ];

export default gdi_routes;

